# Permalinks
permalink:      /:year/:title

# Setup
title:          The Web Riddle
paginate:       5
baseurl:        "/"
url:            "http://thewebriddle.com"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Sam Davyson
  url:          http://davyson.com
  email:        web@davyson.com

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/samdavyson/samdavyson.github.io

# Gems
plugins:
  - jekyll-paginate
